# Generated by Django 2.2.3 on 2019-07-15 06:52

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', '음식'), ('CAR', '자동차'), ('ETC', '기타')], default='대표 카테고리', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mapmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=blog.models.user_path)),
                ('comment', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='없음', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category')),
                ('owner', models.ForeignKey(default='unknow|default 유저', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
