# Generated by Django 2.2.3 on 2019-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('FOOD', '음식'), ('CAR', '자동차'), ('ETC', '기타')], default='카테고리', max_length=10),
        ),
    ]
