# Generated by Django 2.2.3 on 2019-07-19 11:37

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_path),
        ),
    ]
