# Generated by Django 2.2.3 on 2019-07-26 14:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190725_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.user_path),
        ),
    ]
